# Generated by Django 4.0.4 on 2022-04-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compromisso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compromisso', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_termino', models.TimeField()),
                ('local', models.CharField(max_length=255)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
