# Generated by Django 4.0.4 on 2022-04-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaCompromissos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compromisso', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_termino', models.TimeField()),
                ('local', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[('a', 'Agendado'), ('r', 'Realizado'), ('c', 'Cancelado')])),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'AgendaCompromissos',
            },
        ),
    ]
