# Generated by Django 4.0.4 on 2022-04-22 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromisso',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compromisso',
            name='hora_inicio',
            field=models.TimeField(verbose_name='Hora do inicio'),
        ),
        migrations.AlterField(
            model_name='compromisso',
            name='hora_termino',
            field=models.TimeField(verbose_name='Hora do termino'),
        ),
    ]
