# Generated by Django 4.0.4 on 2022-05-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_agendacompromissos_compromisso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendacompromissos',
            name='hora_inicio',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='agendacompromissos',
            name='hora_termino',
            field=models.TimeField(),
        ),
    ]
